-- ADD SQL COMMANDS HERE --
DROP TABLE IF EXISTS snacks;

CREATE TABLE snacks (
    id INTEGER PRIMARY KEY,
    name VARCHAR(40) NOT NULL,
    type VARCHAR(25) NOT NULL,
    description TEXT(1000),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);
